name: update
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Download secret json from S3
        run: aws s3 cp s3://fitness-tracker-blobs/pc-api-9217576884676944131-660-c3f177bf72d7.json ./pc-api-9217576884676944131-660-c3f177bf72d7.json

      - name: Grant gradlew execution permission
        working-directory: ./android
        run: chmod +x ./gradlew

      - name: Build release
        working-directory: ./android
        run: ./gradlew bundleRelease

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: pc-api-9217576884676944131-660-c3f177bf72d7.json
          packageName: fitness.tracker
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: internal